// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first terms will be:
// 1,2,3,5,8,13,21,34,55,89
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let fib =
    Seq.unfold (fun (a,b) -> Some(a+b, (b, a+b))) (0,1)
    
fib
|> Seq.takeWhile(fun x -> x<4_000_000)
|> Seq.filter(fun x -> x % 2 = 0)
|> Seq.sum
|> printf "Sum: %d"